version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /examples/astro-project/ui
    schedule:
      interval: weekly
    labels:
      - dependencies