name: Lint

on:
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Verify formatting
        run: |
          ~/v/v fmt -no-migrate-json2 -verify ~/.vmodules/pushpak_jaiswal/webview || {
            ~/v/v fmt -no-migrate-json2 -diff ~/.vmodules/pushpak_jaiswal/webview
            exit 1
          }

  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Vet
        run: ~/v/v vet -W ~/.vmodules/pushpak_jaiswal/webview

  check-md:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libcurl4-openssl-dev
          version: 1.0
      - name: Check markdown
        run: ~/v/v check-md -hide-warnings ~/.vmodules/pushpak_jaiswal/webview
